services:
  postgres:
    image: postgres:16
    container_name: tienda_postgres
    restart: always
    environment:
      POSTGRES_USER: tienda_admin
      POSTGRES_PASSWORD: tienda123
      POSTGRES_DB: tienda_virtual
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: tienda_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tienda.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: